# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Generate output workflow

on: workflow_dispatch


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run dev

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Data source updated generating new output
        committer: dxong96 <ongdexing@gmail.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: true
        branch: auto/update_${{ steps.date.outputs.date }}
        delete-branch: true
        title: 'Check new update ${{ steps.date.outputs.date }}'
        labels: |
          exports
          automated
        reviewers: dxong96
